<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Models\NextOfKin;
use App\Models\Loan;
use App\Models\AgentAccessCode;

#[Fillable([
    'name',
    'email',
    'phone',
    'id_number',
    'employment_status',
    'monthly_income',
    'wallet_id',
    'selfie_path',
    'id_photo_path',
    'password',
    'is_admin',
    'is_agent',
])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'monthly_income' => 'decimal:2',
            'is_admin' => 'boolean',
            'is_agent' => 'boolean',
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONSHIPS
    |--------------------------------------------------------------------------
    */

    // Loans where user is the borrower
    public function loans()
    {
        return $this->hasMany(Loan::class);
    }

    // Latest loan for the user
    public function latestLoan()
    {
        return $this->hasOne(Loan::class)->latestOfMany();
    }

    // Active loan
    public function activeLoan()
    {
        return $this->hasOne(Loan::class)
                    ->whereIn('status', ['active', 'pending'])
                    ->latestOfMany();
    }

    // Loans handled by this agent
    public function agentLoans()
    {
        return $this->hasMany(Loan::class, 'agent_id', 'id');
    }

    // Access codes generated by this agent
    public function accessCodes()
    {
        return $this->hasMany(AgentAccessCode::class, 'sales_agent_id', 'id');
    }

    // Latest code generated by agent
    public function latestAccessCode()
    {
        return $this->hasOne(AgentAccessCode::class, 'sales_agent_id', 'id')->latestOfMany();
    }

    // Next of kin
    public function nextOfKin()
    {
        return $this->hasMany(NextOfKin::class);
    }

    /*
    |--------------------------------------------------------------------------
    | ROLE HELPERS
    |--------------------------------------------------------------------------
    */

    public function isAdmin(): bool
    {
        return $this->is_admin === true;
    }

    public function isAgent(): bool
    {
        return $this->is_agent === true;
    }

    /*
    |--------------------------------------------------------------------------
    | LOAN LOGIC
    |--------------------------------------------------------------------------
    */

    // Dynamic loan limit based on previous repayments
    public function getLoanLimitAttribute(): int
    {
        $base = 500;
        $level = 0;

        $paidLoans = $this->loans()
                          ->where('status', 'paid')
                          ->orderBy('disbursed_at')
                          ->get();

        $count = 0;

        foreach ($paidLoans as $loan) {
            if ($loan->principal == $base + ($level * 500)) {
                $count++;
            }

            if ($count >= 3) {
                $level++;
                $count = 0;
            }
        }

        return $base + ($level * 500);
    }

    // Count repaid loans at current level
    public function repaidAtCurrentLevel(): int
    {
        $currentLimit = $this->loan_limit;

        return $this->loans()
                    ->where('status', 'paid')
                    ->where('principal', $currentLimit)
                    ->count();
    }
}